#!/bin/bash
# One-time VM setup guide for automated testing with UTM
# Run this after creating VMs in UTM

set -e

echo "=== Local MDM VM Setup Guide (UTM) ==="
echo ""

# Check if UTM is installed
if ! command -v utmctl &> /dev/null; then
    echo "✗ UTM not found"
    echo ""
    echo "Install UTM:"
    echo "  brew install --cask utm"
    echo ""
    exit 1
fi

echo "✓ UTM installed ($(utmctl --version 2>/dev/null || echo 'version unknown'))"
echo ""

# Get host IP
HOST_IP=$(ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{print $2}' | head -1)
echo "Your Mac's IP address: $HOST_IP"
echo "VMs will access MDM server at: http://$HOST_IP:8080"
echo ""

CONFIG_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_FILE="$CONFIG_DIR/.vm_config"

# List existing UTM VMs
echo "Existing UTM VMs:"
utmctl list 2>/dev/null || echo "  (none)"
echo ""

echo "=== Step 1: Create VMs in UTM ==="
echo "----------------------------------------"
echo ""
echo "If you haven't created the VMs yet:"
echo ""
echo "  macOS VM:"
echo "    1. UTM → Create New VM → Virtualize → macOS"
echo "    2. Select IPSW: tests/device-testing/images/macos-26.ipsw"
echo "    3. Settings: 2 CPU cores, 4 GB RAM, 30 GB disk"
echo "    4. Name it: LocalMDM-macOS-Test"
echo ""
echo "  Windows VM:"
echo "    1. UTM → Create New VM → Virtualize → Windows"
echo "    2. Select ISO: tests/device-testing/images/Win11_25H2_English_Arm64.iso"
echo "    3. Check 'Install drivers and SPICE tools'"
echo "    4. Settings: 2 CPU cores, 4 GB RAM, 40 GB disk"
echo "    5. Name it: LocalMDM-Windows-Test"
echo ""
read -p "Have you created both VMs and completed OS installation? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Please create VMs first, then run this script again."
    exit 1
fi

# macOS VM setup
echo ""
echo "=== Step 2: macOS VM Setup ==="
echo "----------------------------------------"
echo "In the macOS VM, open Terminal and run:"
echo ""
echo "  # Enable SSH"
echo "  sudo systemsetup -setremotelogin on"
echo ""
echo "  # Get IP address"
echo "  ifconfig | grep 'inet '"
echo ""
read -p "Enter macOS VM IP address: " MACOS_IP

echo "Testing SSH connection..."
if ssh -o ConnectTimeout=5 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null testuser@$MACOS_IP "echo 'SSH OK'" 2>/dev/null; then
    echo "✓ macOS SSH connection successful"
else
    echo "⚠ SSH connection failed — verify SSH is enabled and IP is correct"
    echo "  Continuing anyway (you can fix this later)"
fi

# Windows VM setup
echo ""
echo "=== Step 3: Windows VM Setup ==="
echo "----------------------------------------"
echo "In the Windows VM, open PowerShell as Administrator and run:"
echo ""
echo "  # Enable WinRM for remote management"
echo "  Enable-PSRemoting -Force"
echo "  Set-Item WSMan:\\localhost\\Service\\AllowUnencrypted -Value \$true"
echo "  Set-Item WSMan:\\localhost\\Client\\TrustedHosts -Value '*' -Force"
echo ""
echo "  # Enable OpenSSH Server (optional, for SSH access)"
echo "  Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0"
echo "  Start-Service sshd"
echo "  Set-Service -Name sshd -StartupType Automatic"
echo ""
echo "  # Get IP address"
echo "  ipconfig"
echo ""
read -p "Enter Windows VM IP address: " WINDOWS_IP

# Save config
cat > "$CONFIG_FILE" << EOF
# VM Configuration (generated by setup_vms.sh)
MACOS_VM_NAME=LocalMDM-macOS-Test
WINDOWS_VM_NAME=LocalMDM-Windows-Test
MACOS_IP=$MACOS_IP
WINDOWS_IP=$WINDOWS_IP
HOST_IP=$HOST_IP
EOF

echo ""
echo "✓ Configuration saved to: $CONFIG_FILE"

# Create SSH config
echo ""
echo "=== Step 4: SSH Config ==="
echo "----------------------------------------"
mkdir -p ~/.ssh
cat > ~/.ssh/config.localmdm << EOF
Host localmdm-macos
    HostName $MACOS_IP
    User testuser
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null

Host localmdm-windows
    HostName $WINDOWS_IP
    User testuser
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
EOF

echo "✓ SSH config created at ~/.ssh/config.localmdm"
echo ""
echo "Add to your ~/.ssh/config:"
echo "  Include ~/.ssh/config.localmdm"

# Summary
echo ""
echo "=== Setup Complete! ==="
echo "----------------------------------------"
echo ""
echo "VM Access:"
echo "  macOS:   ssh localmdm-macos"
echo "  Windows: ssh localmdm-windows (if OpenSSH installed)"
echo "           or use WinRM from test scripts"
echo ""
echo "MDM Server: http://$HOST_IP:8080"
echo ""
echo "Next steps:"
echo "  1. Start Docker stack:  make docker-up && sleep 45 && make migrate-up && make seed"
echo "  2. Start MDM server:    make run"
echo "  3. Run tests:           ./scripts/run_all_tests.sh"
echo ""
echo "To reset VMs to clean state:"
echo "  ./scripts/restore_vms.sh"
echo "  (Uses UTM clone from template — see restore_vms.sh for details)"
